// Generated by CoffeeScript 1.6.2
(function() {
  describe("AI algorithm", function() {
    var ai;

    ai = void 0;
    beforeEach(function() {
      ai = new Computer;
      spyOn(ai, 'winningLocation').andReturn(false);
      spyOn(ai, 'blockLocation').andReturn(false);
      spyOn(ai, 'blockDoubleThreatLocation').andReturn(false);
      spyOn(ai, 'playCenterLocation').andReturn(false);
      spyOn(ai, 'playOppositeCornerLocation').andReturn(false);
      spyOn(ai, 'playAnyCornerLocation').andReturn(false);
      return spyOn(ai, 'playWallLocation').andReturn(false);
    });
    it("plays the winning move if it can win", function() {
      ai.winningLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.winningLocation).toHaveBeenCalled();
    });
    it("blocks the player if a winning move cannot be played", function() {
      ai.blockLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.blockLocation).toHaveBeenCalled();
    });
    it("blocks a double threat opportunity if the computer cannot create a double threat", function() {
      ai.blockDoubleThreatLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.blockDoubleThreatLocation).toHaveBeenCalled();
    });
    it("plays the center space if there is no threat of double threat", function() {
      ai.playCenterLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.playCenterLocation).toHaveBeenCalled();
    });
    it("plays the opposite corner from the player if the center is taken", function() {
      ai.playOppositeCornerLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.playOppositeCornerLocation).toHaveBeenCalled();
    });
    it("plays any corner if the player has not take a corner", function() {
      ai.playAnyCornerLocation.andReturn(true);
      ai.gameLogic();
      return expect(ai.playAnyCornerLocation).toHaveBeenCalled();
    });
    return it("plays a wall spot if no corners are available", function() {
      ai.gameLogic();
      return expect(ai.playWallLocation).toHaveBeenCalled();
    });
  });

}).call(this);
