// Generated by CoffeeScript 1.6.2
(function() {
  var Game;

  Game = (function() {
    function Game(firstPlayer, secondPlayer, board, firstTurn) {
      this.firstPlayer = firstPlayer;
      this.secondPlayer = secondPlayer;
      this.board = board;
      if (firstTurn == null) {
        firstTurn = this.firstPlayer;
      }
      this.gameOver = false;
      this.turn = firstTurn;
    }

    Game.prototype.playerMove = function(location) {
      var result;

      if (this.turn === this.firstPlayer) {
        result = this.board.firstPlayerMove(location);
      }
      if (this.turn === this.secondPlayer) {
        result = this.board.secondPlayerMove(location);
      }
      if (result) {
        this.changeTurn();
      }
      return result;
    };

    Game.prototype.changeTurn = function() {
      return this.turn = this.turn === this.firstPlayer ? this.secondPlayer : this.firstPlayer;
    };

    Game.prototype.checkGameOver = function() {
      this.winner = this.board.checkForWinner();
      if (this.winner !== false) {
        this.gameOver = true;
      }
      if (this.board.checkForDraw()) {
        this.gameOver = true;
        return this.winner = "Nobody";
      }
    };

    return Game;

  })();

  window.Game = Game;

}).call(this);
