// Generated by CoffeeScript 1.6.2
(function() {
  var Game;

  Game = (function() {
    Game.prototype.board = [" ", " ", " ", " ", " ", " ", " ", " ", " "];

    function Game(player) {
      this.player = player;
    }

    Game.prototype.playerMove = function(position) {
      if (this.checkLocation(position) === " ") {
        return this.board[position] = "X";
      }
    };

    Game.prototype.checkLocation = function(position) {
      return this.board[position];
    };

    Game.prototype.computerMove = function() {
      var position;

      position = this.computerLogic();
      if (this.checkLocation(position) === " ") {
        return this.board[position] = "O";
      }
    };

    Game.prototype.computerLogic = function() {};

    return Game;

  })();

  window.Game = Game;

}).call(this);
