// Generated by CoffeeScript 1.6.2
(function() {
  var computerMove, game, playerMove, resetBoard, setPieces, startGame;

  game = void 0;

  startGame = function() {
    var firstMove, name, playerToken;

    name = $('#playerName').val();
    if (name === "") {
      name = "player1";
    }
    firstMove = $('#firstMove').val();
    playerToken = $('#playerPiece').val();
    game = new Game(name, firstMove, playerToken);
    return resetBoard();
  };

  resetBoard = function() {
    var space, _i, _results;

    _results = [];
    for (space = _i = 0; _i <= 8; space = ++_i) {
      $("div#space" + space).removeClass('cross');
      _results.push($("div#space" + space).removeClass('circle'));
    }
    return _results;
  };

  computerMove = function() {
    game.computerMove();
    return setPieces();
  };

  playerMove = function(space) {
    game.playerMove(space);
    setPieces();
    return computerMove();
  };

  setPieces = function() {
    var count, space, _i, _len, _ref, _results;

    count = 0;
    _ref = game.board;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      space = _ref[_i];
      if (space === "X") {
        $("div#space" + count).addClass('cross');
      }
      if (space === "O") {
        $("div#space" + count).addClass('circle');
      }
      _results.push(count++);
    }
    return _results;
  };

  $(function() {
    $('#newGame').on("click", function(event) {
      startGame();
      if (game.turn === "computer") {
        return computerMove();
      }
    });
    return $('.boardPiece').on("click", function(event) {
      var location;

      location = this.id.slice(-1);
      return playerMove(location);
    });
  });

}).call(this);
