// Generated by CoffeeScript 1.6.2
(function() {
  var board, checkTurn, firstPlayer, game, gameResults, playerMove, resetBoard, secondPlayer, setPieces, startGame;

  firstPlayer = secondPlayer = board = game = void 0;

  startGame = function() {
    var firstMove, firstPlayerToken, secondPlayerToken, startingPlayer;

    firstPlayerToken = $('#playerPiece').val() === "X" ? "X" : "O";
    secondPlayerToken = $('#playerPiece').val() === "X" ? "O" : "X";
    board = new Board(firstPlayerToken, secondPlayerToken);
    firstPlayer = new Player("firstPlayer");
    secondPlayer = new Computer(board);
    firstMove = $("#firstMove").val();
    console.log(firstMove);
    startingPlayer = firstMove === "player" ? firstPlayer : secondPlayer;
    game = new Game(firstPlayer, secondPlayer, board, startingPlayer);
    return resetBoard();
  };

  resetBoard = function() {
    var space, _i, _results;

    _results = [];
    for (space = _i = 0; _i <= 8; space = ++_i) {
      $("div#space" + space).removeClass('cross');
      _results.push($("div#space" + space).removeClass('circle'));
    }
    return _results;
  };

  playerMove = function(space) {
    if (!game.gameOver) {
      game.playerMove(space);
      setPieces();
      return gameResults();
    }
  };

  gameResults = function() {
    game.checkGameOver();
    if (game.gameOver) {
      return alert("" + game.winner + " wins!");
    }
  };

  checkTurn = function() {
    if (game.turn === secondPlayer) {
      return playerMove(secondPlayer.findBestMove());
    }
  };

  setPieces = function() {
    var count, space, _i, _len, _ref, _results;

    count = 0;
    _ref = board.spaces;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      space = _ref[_i];
      if (space === "X") {
        $("div#space" + count).addClass('cross');
      }
      if (space === "O") {
        $("div#space" + count).addClass('circle');
      }
      _results.push(count++);
    }
    return _results;
  };

  $(function() {
    $('#newGame').on("click", function(event) {
      startGame();
      return checkTurn();
    });
    return $('.boardPiece').on("click", function(event) {
      var location;

      location = this.id.slice(-1);
      playerMove(location);
      return checkTurn();
    });
  });

}).call(this);
