// Generated by CoffeeScript 1.6.2
(function() {
  var Player;

  Player = (function() {
    function Player(name) {
      this.name = name;
    }

    return Player;

  })();

  window.Player = Player;

}).call(this);
